### ISSUE TITLE
how can I get the logger_test_10hp.csv?

### ISSUE THREAD

**Issue by xuanmaione** [gustavomoers/CollisionAvoidance-Carla-DRL-MPC#5]
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\CollisionAvoidance-Carla-DRL-MPC-main\\logsx9461045-recurrentPPO-90kmh-transfer\\evaluation/logger_test_10hp.csv'
I cant get the file

**Comment by gustavomoers** [comment]
Hello,
This is log file used for testing, not important for training.
You should set  self.logger = False at line 81 on file World.py

**Comment by lbs-yyds** [comment]
self.blueprint_library = self.world.get_blueprint_library()
ValueError: role_name: colors must have 3 channels (R,G,B)

**Comment by gustavomoers** [comment]
this must be related to Carla version, please refer to [ValueError: role_name: colors must have 3 channels (R, G, B) occurs when using get_blueprint_library(). #7939 ](https://github.com/carla-simulator/carla/issues/7939)
